name: .NET Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        runtime: [win-x64, linux-x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET 9
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.x'

    - name: Restore dependencies
      run: dotnet restore AutoTelegramBackuper.CLI/AutoTelegramBackuper.CLI.csproj

    - name: Build
      run: dotnet build AutoTelegramBackuper.CLI/AutoTelegramBackuper.CLI.csproj --configuration Release --no-restore

    - name: Publish
      run: dotnet publish AutoTelegramBackuper.CLI/AutoTelegramBackuper.CLI.csproj --configuration Release --output ./publish --runtime ${{ matrix.runtime }}

    - name: Zip the build output
      run: |
        if [ "${{ matrix.os }}" == "windows-latest" ]; then
          7z a AutoTelegramBackuper.CLI-${{ matrix.runtime }}.zip ./publish/*
        else
          zip -r AutoTelegramBackuper.CLI-${{ matrix.runtime }}.zip ./publish/*
        fi

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AutoTelegramBackuper.CLI-${{ matrix.runtime }}-${{ github.run_id }}-${{ github.run_attempt }}
        path: AutoTelegramBackuper.CLI-${{ matrix.runtime }}.zip
        if-no-files-found: warn
        compression-level: 6
        overwrite: false
        include-hidden-files: false

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: AutoTelegramBackuper.CLI-win-x64-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./artifacts/win-x64

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: AutoTelegramBackuper.CLI-linux-x64-${{ github.run_id }}-${{ github.run_attempt }}
        path: ./artifacts/linux-x64

    - name: Release to GitHub
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./artifacts/win-x64/AutoTelegramBackuper.CLI-win-x64-${{ github.run_id }}-${{ github.run_attempt }}.zip
          ./artifacts/linux-x64/AutoTelegramBackuper.CLI-linux-x64-${{ github.run_id }}-${{ github.run_attempt }}.zip
      env:
        GITHUB_TOKEN: ${{ secrets.ATB_TOKEN }}
